### ISSUE TITLE
How to filter keyword by regex_patern of folder?

### ISSUE THREAD

**Issue by Tej12345** [nvim-telescope/telescope-live-grep-args.nvim#19]
**Telescope live_grep** is missing the feature when you could find a grep pattern in particular folders.(regex folders)

I want to see something like:
1.  ```Telescope live_grep```
2.  Write into input box e.g.: ```define --folder "*playground*```
3. Get results of **define** keyword in under everyfolder which has **playground** keyword.

It's really annoying to do this by going to:
1) Move results to quickfix window (Pressing C-q)
2) Filtering results with ```:Cfilter playgound```

Please, this nvim plugin is really great so far, but this feature I MISS so much...
Thank you, Nikita

**Comment by weeman1337** [comment]
Hi @Tej12345 thanks for your questions.

Assuming you are running `rg` you can do this:

- `"define" playground` → search for `define` under `./playground`
- `-g *playground* define → search for `define` in files matching the glob pattern

For more examples you can also check the [ripgrep guide](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-globs)

If that is what you've been looking for just close the issue.

**Comment by Tej12345** [comment]
Thank you, man!

**Comment by weeman1337** [comment]
I may add some examples to the README. So please keep the issue open.

**Comment by johhnsmmith198** [comment]
Hey @weeman1337 I sometimes need to search on a sibling folder. For instance `-g ../other-project/** define` but this doesn't work. any advise of how to target a specific folder with your extension?
rg would allow a path at the end of the command

In this example, we didn't specify a file at all. Instead, ripgrep defaulted to searching your current directory in the absence of a path. In general, `rg foo` is equivalent to `rg foo ./.`

**Comment by weeman1337** [comment]
Hi @johhnsmmith198 :wave: 

I think `-g` does not work because it defines a glob in the search path. As you found out it is `./.`.  
So defining another path should work: `"define" ../other-project`

I am currently working on a shortcut to quote the current prompt. So that adding path/params will be easier.

**Comment by johhnsmmith198** [comment]
Hey @weeman1337 
You can try it, it doesn't work.
Something that works is: `"define" ../`
but as soon as I explicitly state a folder: `"define" ../project/` or `"define" ../project/**` it doesn't work anymore

**Comment by weeman1337** [comment]
Works for me (where cwd is not `engelsystem`):

![grafik](https://user-images.githubusercontent.com/6216686/174429154-3871b07d-2ba9-4591-b47f-b59d707410cf.png)

Does it work from the shell?

**Comment by johhnsmmith198** [comment]
sorry you are right.
I took it step by step and did it in the terminal than again in nvim and yes it works. 
Thank you so much. Excellent plugin !
