### ISSUE TITLE
The plugin url is wrong on the deprecation message

### ISSUE THREAD

**Issue by danielo515** [nvim-telescope/telescope-live-grep-args.nvim#20]
Hello, thanks for this new incarnation of the plugin.
However, the reference in the warning message points to a wrong repository, it is using underscores instead of dashes for the plugin name.
I think this can be confusing.
Thanks

**Comment by Conni2461** [comment]
CC @weeman1337 should be fixed today. I can do that this evening

**Comment by weeman1337** [comment]
ARGH - I'm on it…

**Comment by weeman1337** [comment]
Done by https://github.com/nvim-telescope/telescope-live-grep-args.nvim/commit/77d53b25ef6eb080845b1dac8337cac0be6b9114
