### ISSUE TITLE
passing a default string value when opening?

### ISSUE THREAD

**Issue by gilbh** [nvim-telescope/telescope-live-grep-args.nvim#25]
Hi,

Is it possible to pass the string/pattern to be searched?
Something link:
```
:lua require("telescope").extensions.live_grep_args.live_grep_args({value=[STRING_TO_SEARCH]})
```

Thanks!

**Comment by weeman1337** [comment]
Hi @gilbh :wave: 

Yes, it is: `:lua require("telescope").extensions.live_grep_args.live_grep_args({default_text="test"})`

**Comment by gilbh** [comment]
Thanks!

(I couldn't locate instructions on arguments, is there one and where?)
