### ISSUE TITLE
Disable default mappings

### ISSUE THREAD

**Issue by Tej12345** [nvim-telescope/telescope-live-grep-args.nvim#26]
Please add the ability to disable default mappings.
Since Ctrl-K for me is mapped to cycle through telescope history, but telescope-live-grep-args forces its behaviour...
```
local default_mappings = {
  i = {
    ["<C-k>"] = actions.quote_prompt(), -- k for kwote :D - q is already taken
    ["<C-l>g"] = actions.quote_prompt({ postfix = ' --iglob ' }), -- l for live grep args; g for glob
    ["<C-l>t"] = actions.quote_prompt({ postfix = ' -t' }), -- l for live grep args; t for type
  },
}

local live_grep_args = function(opts)
  opts = vim.tbl_extend("force", setup_opts, opts or {})
  opts.mappings = vim.tbl_deep_extend("force", default_mappings, opts.mappings or {})
```

**Comment by weeman1337** [comment]
Hey @Tej12345 thanks for raising this issue.

I thought about shortcuts and came to this conclusion:
- There should be only the bare minimum of shortcuts defined per default.
  - I would remove everything except ctrl + k, becaus I know that many people find this handy ootb.
- Default shortcuts should be overridable.
- There should be an option to disable all default shortcuts.

**Comment by weeman1337** [comment]
@Tej12345 can you give #30 a try? Will merge it after some testing.

**Comment by gegoune** [comment]
I, on the other hand, am against that breaking change. Ability to disable default mappings is a non-breaking change that requires nothing from majority of users which most of the time use default mappings set by plugins. Those unhappy with default one should be given an option to either override existing mappings one by one or get plugins not to set them in the first place.

**Comment by benwoodward** [comment]
> Everything except <C-k> will be removed. for sure <C-k> is a „basic“ shortcut.

I use `<C-k>` to move the file selection up when using `rg`, `fzf` etc.—would be great if I could override this built-in mapping.

**Comment by matteha** [comment]
> > Everything except  will be removed. for sure  is a „basic“ shortcut.
> 
> I use `<C-k>` to move the file selection up when using `rg`, `fzf` etc.—would be great if I could override this built-in mapping.

Same here, also using C-k to navigate popup menus. It's been recommended as keybinding for e.g. cmp autocomplete as well for a while. Great plugin, thanks!

**Comment by weeman1337** [comment]
Hi @benwoodward , @matteha you can override/disable the default mappings as described in the [configuration section](https://github.com/nvim-telescope/telescope-live-grep-args.nvim#configuration). Just use `default_mappings` to change them.

**Comment by weeman1337** [comment]
Also see this issue https://github.com/nvim-telescope/telescope-live-grep-args.nvim/issues/34

**Comment by benwoodward** [comment]
> Hi @benwoodward , @matteha you can override/disable the default mappings as described in the [configuration section](https://github.com/nvim-telescope/telescope-live-grep-args.nvim#configuration). Just use `default_mappings` to change them.

fantastic. thank you. and thanks for putting this plugin together!
