### ISSUE TITLE
Disable default mappings

### ISSUE THREAD

**Issue by suyby** [nvim-telescope/telescope-live-grep-args.nvim#34]
**Can't close even if default mapping is overridden.**
Below is my configuration：
```
local telescope = require("telescope")
local lga_actions = require("telescope-live-grep-args.actions")

telescope.setup {
  extensions = {
    live_grep_args = {
      auto_quoting = true, -- enable/disable auto-quoting
      mappings = {
        i = {
          ["<C-l>"] = lga_actions.quote_prompt(),
        }
      }
    }
  }
}
```

**Comment by weeman1337** [comment]
Hi @matrix-f . If you don't want to use the default mappings, you have to override them:

```lua
local telescope = require("telescope")
local lga_actions = require("telescope-live-grep-args.actions")

telescope.setup {
  extensions = {
    live_grep_args = {
      auto_quoting = true, -- enable/disable auto-quoting
      default_mappings = {
        i = {
          ["<C-l>"] = lga_actions.quote_prompt(),
        }
      }
    }
  }
}
```

`mappings` → `default_mappings` as mentioned in the [configuration section](https://github.com/nvim-telescope/telescope-live-grep-args.nvim#configuration).

Can you give it a try and report back if it works for you?

**Comment by matrix-f** [comment]
Sorry, even as you mean, the default map key (<C-k>) still works, and the custom shortcut <C-l> doesn't work.

**Comment by weeman1337** [comment]
I gave [this](https://github.com/nvim-telescope/telescope-live-grep-args.nvim/issues/34#issuecomment-1233927630) a fresh test this morning and it is working fine. Did you call `telescope.load_extension("live_grep_args")` after setup @matrix-f ?
`

**Comment by matrix-f** [comment]
@weeman1337 Thanks a lot, it's really a version issue. After the version update, the problem is solved, thank you again!

**Comment by fzhzhen1987** [comment]
i get the same problem. Changing the default keymap,but not work.

![Snipaste_2022-11-04_15-26-21](https://user-images.githubusercontent.com/40282264/199906215-76edbc57-b395-4b16-b4bd-4b38e4759444.png)

**Comment by fzhzhen1987** [comment]
Just a little advise:
1 why not disable by default
2 change the default keybind ,contradicted with the default keybind of telescope

**Comment by weeman1337** [comment]
Hi @fzhzhen1987 looks like you missed `default_mappings = {}`.
Anyway this issue is still open because I am going to remove all default mappings soon.

**Comment by fzhzhen1987** [comment]
Thank u for ur answer.
local lga_actions = require("telescope-live-grep-args.actions")

>looks like you missed default_mappings = {}.
I tested bind ctrl-l for default_mappings = {}.But Ctrl-k and Ctrl-l get the same func.
Ctrl-k still works.....

>Anyway this issue is still open because I am going to remove all default mappings soon.
waiting for that commit. Telescope is very gooood. By the way do u have the plan to build gtags pickers?
Thank u again.

**Comment by weeman1337** [comment]
> By the way do u have the plan to build gtags pickers?

That would be a question to be asked in the [main Telescope tracker](https://github.com/nvim-telescope/telescope.nvim/issues).

**Comment by weeman1337** [comment]
@fzhzhen1987  can you give this branch a try? https://github.com/nvim-telescope/telescope-live-grep-args.nvim/pull/38

**Comment by fzhzhen1987** [comment]
@weeman1337 
good morning.
I tested commit 1d2137a1ad Remove default mappings.
Default keybind is gone.
Thank u.
