### ISSUE TITLE
[FEATURE REQUEST] Support telescope's grep_string option as well with args 

### ISSUE THREAD

**Issue by vignesh0025** [nvim-telescope/telescope-live-grep-args.nvim#35]
Hi,

We have a telescope.builtin.grep_string() that searches the word under the cursor. It would be nice to add support for "grep_string()" as well.

Usecase:
In big C based projects which doesn't have support for compile_commands.json, it will be easier to give options like "-g *.c" or "-g *.h" to search only in those files and avoid logs files.

**Comment by weeman1337** [comment]
Hi @vignesh0025 thank you for opening this issue.

Do you mean something like this https://github.com/nvim-telescope/telescope-live-grep-args.nvim/pull/23 ?

**Comment by vignesh0025** [comment]
@weeman1337 yes precisely. Closing this issue.
