### ISSUE TITLE
Support `to_fuzzy_refine` function

### ISSUE THREAD

**Issue by bangedorrunt** [nvim-telescope/telescope-live-grep-args.nvim#39]
Hi, 

Current built-in `rg` has `to_fuzzy_refine` which allow us to narrow down our search. It'd be great if we could use it for this extension. 

Related: https://github.com/nvim-telescope/telescope.nvim/pull/2034

**Comment by taybart** [comment]
I tested this and it worked with the current version

**Comment by ragu-manjegowda** [comment]
It would be nice to have this support `toggle` between `to_fuzzy_refine` and `live_grep_args`.

When in `to_fuzzy_refine`, is it possible to go back to `live_grep_args` and search for something new?

**Comment by ilan-schemoul** [comment]
Yeah it works in the setup of Telescope you can write
 ```lua
 extensions = {
    live_grep_args = {
      auto_quoting = true, -- enable/disable auto-quoting
      mappings = { -- extend mappings
        i = {
          ["<C-space>"] = actions.to_fuzzy_refine,
          ["<C-k>"] = lga_actions.quote_prompt(),
          ["<C-i>"] = lga_actions.quote_prompt({ postfix = " --iglob " }),
        },
      },
    },
  },
```
It should be part of the read as C-space is already the default in Telescope live_grep

**Comment by weeman1337** [comment]
Support is given if you create a shortcut.

Closed by https://github.com/nvim-telescope/telescope-live-grep-args.nvim/pull/80 , that documents it in the README
