### ISSUE TITLE
Live grep does not give any result

### ISSUE THREAD

**Issue by bellaichef** [nvim-telescope/telescope-live-grep-args.nvim#43]
Hi,

I'm using telescope under nvim 0.9.

Everything works fine but live grep.

Here are the installed packages : 
![Screenshot from 2023-01-06 17-28-38](https://user-images.githubusercontent.com/45790724/211055165-fb15076c-300a-4bac-978e-d032079f14c6.png)

So there is : 

- Telescope
- Plenary
- Ripgrep

Here is my plugins conf (only the telescope part) : 

![Screenshot from 2023-01-06 17-34-16](https://user-images.githubusercontent.com/45790724/211055849-e99e2eb3-84d2-4c55-b06d-bddc3ad0e1f5.png)

This should be enough, no ? Do I miss something ?

For info, the find files in Telescope works without any issue.

Is there any log for telescope to debug these kind of behaviour.

Thanks by advance for any help or suggestion.

**Comment by bellaichef** [comment]
Found what was going wrong ripgrep has to be installed first : https://github.com/BurntSushi/ripgrep

I thought that neovim plugin would be enough but I'll a little bit new on it.

**Comment by weeman1337** [comment]
Thanks for reporting back @bellaichef . Maybe it would make sense to implement a dependency check.

**Comment by bellaichef** [comment]
You are welcome. 

Something like : 

```
if vim.fn.empty(vim.fn.glob('/usr/bin/rg')) > 0 then
-- Whatever you want to do --
end
```

Should to the trick but I'm pretty sure that you already know what to do! ;-)
