### ISSUE TITLE
find-files-args

### ISSUE THREAD

**Issue by masriomarm** [nvim-telescope/telescope-live-grep-args.nvim#46]
May i suggest you to start passing args to fd as rg?

**Comment by weeman1337** [comment]
Hello @masriomarm . Unfortunately I don't understand what you mean. Can you explain more?

**Comment by masriomarm** [comment]
Hello @weeman1337 , Thanks for the great tool. I suggest that you add the ability to pass live arguments to fd utility (find files) as you do with rg.
It's a suggestion not an issue, apologies.
