### ISSUE TITLE
Automatically select the word under cursor when invoking live grep

### ISSUE THREAD

**Issue by weiyshay** [nvim-telescope/telescope-live-grep-args.nvim#51]
Hi,
Thanks for this nice plugin! 

It is common to search for the word under cursor in case definition/reference is not helpful.
Very often the function/variable names are long and it is convenient if the plugin can have them selected when invoking live grep.

Also, it will be nice if a list of the history symbols searched can be prompted, is it possible?

**Comment by weeman1337** [comment]
@weiyshay  do you mean something [like this](https://github.com/nvim-telescope/telescope-live-grep-args.nvim/pull/23) ?

I really have to update that PR and merge it :laughing:

**Comment by weiyshay** [comment]
@weeman1337 Thanks for your respone!

Yes, exactly. I did a quick try on the link but unfortunately it seems that the function changed and I could not make it.
i). name change from 'live_grep_raw' to 'live_grep_args', this is fine.
ii). The arguments changed from the pattern to search to an options which don't include a pattern due to ':help live_grep'

Any tips to work around?

<img width="981" alt="图片" src="https://user-images.githubusercontent.com/99458445/226303194-456c5e64-ed6e-4d55-a8b9-13d6c5f2e3b9.png">

**Comment by weeman1337** [comment]
@weiyshay you can test it by using the branch from [this PR](https://github.com/nvim-telescope/telescope-live-grep-args.nvim/pull/23).

The mapping should look like

```
local live_grep_args_shortcuts = require("telescope-live-grep-args.shortcuts")
keymap.set("n", "<leader>gc", live_grep_args_shortcuts.grep_word_under_cursor)
```

Let me hear how that works for you.

**Comment by weiyshay** [comment]
Michael,
Thank you very much! It works, nice!

<img width="935" alt="图片" src="https://user-images.githubusercontent.com/99458445/229704951-60f483f4-4b9d-4e61-a80b-2ab8adcb6874.png">

<img width="1512" alt="图片" src="https://user-images.githubusercontent.com/99458445/229705007-01d985e2-c29e-45a4-a742-f6a1827b5e78.png">

**Comment by weeman1337** [comment]
This has net yet been merged → reopen until then

**Comment by weiyshay** [comment]
okay.
