### ISSUE TITLE
what's the advantage by using auto_quoting?

### ISSUE THREAD

**Issue by zhengpd** [nvim-telescope/telescope-live-grep-args.nvim#57]
The `auto_quoting` is enable by default. I read the doc and tried disabling it but it seems only enforce user to quote the search string. What's the advantage here? Appreciate if someone gives real search cases to understand the difference.

**Comment by zhengpd** [comment]
Auto quoting helps when search string like "exa -l" which includes hyphen.

**Comment by weeman1337** [comment]
@zhengpd thank you for your question.

Does the [README](https://github.com/nvim-telescope/telescope-live-grep-args.nvim#grep-argument-examples) help?

If there is anything that can be changed to clarify this let me know by a comment here.

**Comment by zhengpd** [comment]
@weeman1337 The examples are fine, but it seems a search string with leading hyphen, quoted or not, won't match anything, For example, the "exa -l" is in one of my files, and searching with `"-l` returns empty result, but `" -l"` got matches (note the leading whitespace).
