### ISSUE TITLE
Does live-grep-args support reading from a `.rgconfig` file?

### ISSUE THREAD

**Issue by DennisTheMenace780** [nvim-telescope/telescope-live-grep-args.nvim#60]
I was looking to tweak my configuration for telescope because often I search for files of the form `myNiftyFile.test.ts` and `myNiftyFile.ts` and i'd like to exclude the test files or exclude the non-test files. So I was thinking of using something like the `.rgconfig` file for specifying unique types and then combining that with something like the live grep actions `quote_prompt()`. 

Additionally, with the `quote_prompt()` [mappings](https://github.com/nvim-telescope/telescope-live-grep-args.nvim#mapping-recipes) should we expect to see the full expansion of the prompt when typing into the live grep UI?

**Comment by weeman1337** [comment]
Yes, it does. 

[See the ripgrep doc for configuration files.](https://github.com/BurntSushi/ripgrep/blob/master/doc/rg.1.txt.tpl#L183)
