### ISSUE TITLE
Not able to register [C-k] mapping for quote_prompt()

### ISSUE THREAD

**Issue by imsaravana369** [nvim-telescope/telescope-live-grep-args.nvim#71]
### Description

I'm using lazy.nvim, I have a `telescope.lua` file wherein I'm trying to configure the [C-K] mapping for quoting the search term, but its not working(following the readme configs)

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

MacOS Ventura V13.2

### Telescope version / branch / rev

0.1.4

### Telescope live grep args version / branch / rev

^1.0.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- WARNING nvim-treesitter not found. 

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `ht` ~
- No healthcheck provided

Telescope Extension: `live_grep_args` ~
- No healthcheck provided
```

### Expected behavior

Quote the search term on clicking <C-k>

### Actual behavior

Not quoting

### Minimal config

```Lua
{
	'nvim-telescope/telescope.nvim',
	tag = '0.1.4',
	dependencies = {
		'nvim-lua/plenary.nvim',
		{
			"nvim-telescope/telescope-live-grep-args.nvim",
			version = "^1.0.0",
		},
               -- ....
	},
	config = function()
		-- ...
		require("telescope").load_extension("live_grep_args")
	end,

	extensions = {
		live_grep_args = {
			auto_quoting = true, -- enable/disable auto-quoting
			mappings = { -- extend mappings
			   i = {	
				    ["C-k"]  = function() require("telescope-live-grep-args.actions").quote_prompt() end
			}
			},

		},
	},
}
```

**Comment by howarddo2208** [comment]
I couldn't assign any mappings for this extension as well

**Comment by gwenyambira** [comment]
`require("telescope-live-grep-args.actions").quote_prompt()` returns a function. See https://github.com/nvim-telescope/telescope-live-grep-args.nvim/blob/851c0997d55601f2afd7290db0f90dc364e29f58/lua/telescope-live-grep-args/actions/quote_prompt.lua#L18

As you have wrapped this in an anonymous function, the returned function that performs the quoting behaviour is never called.

There are a few ways to handle this:
```lua
["<C-k>"] = function(prompt_bufnr)
    require("telescope-live-grep-args.actions").quote_prompt()(prompt_bufnr)
end,
```
or
```lua
["<C-k>"] = require("telescope-live-grep-args.actions").quote_prompt(),
```
Both work, however you run into the issue of them showing up as `i -> <C-K> -> <anonymous>` in the Telescope WhichKey help menu.
I would therefore suggest:
```lua
local function quote_prompt(prompt_bufnr)
    require("telescope-live-grep-args.actions").quote_prompt()(prompt_bufnr)
end
local function quote_prompt_ignoredir(prompt_bufnr)
    require("telescope-live-grep-args.actions").quote_prompt({ postfix = " --iglob '!**/ignoredir/**'" })(prompt_bufnr)
end
local function quote_prompt_type(prompt_bufnr)
    require("telescope-live-grep-args.actions").quote_prompt({ postfix = " -t " })(prompt_bufnr)
end
-- ...
mappings = {
    i = {
        ["<M-g>"] = quote_prompt,
        ["<M-d>"] = quote_prompt_ignoredir,
        ["<M-t>"] = quote_prompt_type,
    }
}
-- ...
```
This will give you proper descriptions (`i -> <M-t> -> quote_prompt_type`, etc.) based on the function name.

**Comment by imsaravana369** [comment]
for some reason, I'm still not able to register the mappings..

**Comment by gwenyambira** [comment]
```lua 
return {
	"nvim-telescope/telescope.nvim",
	tag = "0.1.4",
	dependencies = {
		"nvim-lua/plenary.nvim",
		{
			"nvim-telescope/telescope-live-grep-args.nvim",
			version = "^1.0.0",
		},
	},
	config = function()
		local telescope = require("telescope")
		telescope.setup({
			extensions = {
				live_grep_args = {
					auto_quoting = true, -- enable/disable auto-quoting
					mappings = { -- extend mappings
						i = {
							["<C-k>"] = require("telescope-live-grep-args.actions").quote_prompt(),
						},
					},
				},
			},
		})
		telescope.load_extension("live_grep_args")
	end,
}

```
I replaced my telescope config with the code above, based on your minimal config, in v0.9.1, ripgrep installed. I opened telescope with `Telescope live_grep_args` and pressed `C-k` and it works as expected... 
Sorry, I'm not sure why it wouldn't work on your setup. Just to clarify, you are opening telescope with `Telescope live_grep_args` and the grep+arg functionality is working when you enter it manually, it is just the quoting shortcut that isn't working? I hope someone can help us here...

**Comment by maerch** [comment]
@gwenyambira 👋  Not the initiator of this issue, but I also cannot make it work on my machine. Neither worked on `0.8.x` nor `0.9.4` of Neovim.

This is my minimal configuration:

```
require'telescope'.load_extension'live_grep_args'

require('telescope').setup{
  extensions = {
    live_grep_args = {
      auto_quoting = true, -- enable/disable auto-quoting
      mappings = { -- extend mappings
        i = {
          ["<C-k>"] = require("telescope-live-grep-args.actions").quote_prompt(),
        },
      },
    },
  }
}
```

After I call `:Telescope live_grep_args` the Live Grep (Args) window opens. I can type, it searches correctly, but nothing happens when I press `<C-k>` (or any other mapping).

**Comment by maerch** [comment]
OK, I figured it out by accident while debugging what was causing my particular issue. No expert at all on Neovim/Lua and never used a telescope extension so far. So it seems that I am just holding it wrong. 

The `load_extension` call has to happen **after** the `setup` call. Maybe it helps other souls out there as well.

**Comment by howarddo2208** [comment]
> OK, I figured it out by accident while debugging what was causing my particular issue. No expert at all on Neovim/Lua and never used a telescope extension so far. So it seems that I am just holding it wrong.
> 
> The `load_extension` call has to happen **after** the `setup` call. Maybe it helps other souls out there as well.

thank u, it works now!

**Comment by gillyb** [comment]
I had the same issue with the mappings, and realized that the mappings worked for me inside the telescope mappings section, and *not* in the extension mappings.

I have it defined like this:
```
local actions = require('telescope.actions')
local lga_actions = require('telescope-live-grep-args.actions')

require('telescope').setup({
  defaults = {
    file_ignore_patterns = { "package-lock.json" },
    layout_strategy = "center",
    theme = 'dropdown',
    mappings = {
      i = {
        -- Move up/down with Ctrl+j/k
        ['<C-j>'] = 'move_selection_next',
        ['<C-k>'] = 'move_selection_previous',
        -- When using 'esc' or 'jk' in insert mode, close the window
        ['<esc>'] = 'close',
        ['jk'] = 'close',
        -- Send all results to a quickfix list
        ['<C-q>'] = actions.send_to_qflist + actions.open_qflist,
        -- Ctrl-u will add quotes to the text, so we can send parameters to ripgrep
        ['<C-u>'] = lga_actions.quote_prompt()
      }
    }
  },
  pickers = {
    -- lots of configs here i removed for brevity ....
  },
  extensions = {
    fzy_native = {
      override_generic_sorter = true,
      override_file_sorter = true
    },
    live_grep_args = {
      auto_quoting = true
    }
  }
```

**Comment by imsaravana369** [comment]
Thanks, @maerch I'm using lazy nvim and solved the isssue by moving the `extensions` field inside the setup (previously i defined it in the same level as the `config` key)

```
return {
	'nvim-telescope/telescope.nvim',
	, config = function()
		require("telescope").setup {
			extensions = {
				live_grep_args = {
					auto_quoting = true, -- enable/disable auto-quoting
					mappings = { -- extend mappings
						i = {
							["<C-k>"] = quote_prompt -- extracted as separate function,
							["<C-d>"] = quote_prompt_ignoredir -- same_here, 
							["<C-t>"] = quote_prompt_type -- same_here_too,
						}
					},

				},
			},
		}
		require("telescope").load_extension("live_grep_args") -- load it after `setup`
	end,
	 
       , -- other configs....

}

```
